import type { Metadata } from 'next'
import './globals.css'
import AudioPlayer from '@/components/AudioPlayer/AudioPlayer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-black'>
      <body>
        {children}
        <AudioPlayer />
      </body>
    </html>
  )
}
