import type { Metadata } from 'next'
import './globals.css'
import AudioPlayer from '@/components/AudioPlayer/AudioPlayer'
import DefaultLayout from '@/components/layout/DefaultLayout'
import 'react-loading-skeleton/dist/skeleton.css'
import Providers from '@/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-black select-none'>
      <body>
        <DefaultLayout>
          <Providers>
            {children}
          </Providers>
        </DefaultLayout>
        <AudioPlayer />
      </body>
    </html>
  )
}
