import type { Metadata } from 'next'
import './globals.css'
import AudioPlayer from '@/components/AudioPlayer/AudioPlayer'
import DefaultLayout from '@/components/layout/DefaultLayout'
import 'react-loading-skeleton/dist/skeleton.css'
import Providers from '@/Providers'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-black select-none'>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body>
        <Providers>
          <DefaultLayout>
            {children}
          </DefaultLayout>
          <AudioPlayer />
        </Providers>
      </body>
    </html>
  )
}
